### ISSUE TITLE
Presentation of the results

### ISSUE THREAD

**Issue by perrier54** [santiagohy/grammar-rules-extraction#1]
In the headers, you must write #P1&P2&P3 instead of #P2&P3. Also, it is weird to put only one absolute value in this array. I would remove it and for simple combinations, I would put the two dimensional array like in the master thesis with all absolute values.

**Comment by s-herrera** [comment]
The entire website has changed. Now the partial results are displayed in the side bar. The results in the table are selectable. Once selected, a 2x2 contigency table with the relevant occurrences will appear.

**Comment by perrier54** [comment]
This doesn't work. The result of the match is not displayed. Then, after the applying P3, no absolute result is displayed (especially P1 & P2 $ P3).

**Comment by perrier54** [comment]
The possibility to go from the application to `Grew-match` via a link is disappeared.

**Comment by s-herrera** [comment]
Normally, i fixed the problem. Now one you select a row, the information has to appear at the side bar, like in the image, with the grew link. Do a `git pull`


![image](https://user-images.githubusercontent.com/95502001/183363326-d0e88b97-2895-4356-9205-ef77f66daa8d.png)
