### ISSUE TITLE
pattern P3

### ISSUE THREAD

**Issue by perrier54** [santiagohy/grammar-rules-extraction#10]
I use the corpus [fr_gsd-sud-train_sud.txt](https://github.com/santiagohy/grammar-rules-extraction/files/9280548/fr_gsd-sud-train_sud.txt)
 I apply the following patterns:
_P1: pattern{G[upos=PROPN]; D[upos=ADJ]}
P2: pattern{G -[mod]-> D}
P3: without{L[upos=PROPN]; L << G; L -[flat@name]-> G}
  without{L[upos=NOUN]; L << G; L -[appos|mod]-> G}_

At the first run, the system returns the following error message : 
_PatternError: The Grew commands (pattern, without, global) or the key patterns (e.g. X.upos) are not acceptable_
If I remove the second without, the system returns a result.

**Comment by s-herrera** [comment]
Fixed!
