### ISSUE TITLE
Modification of patterns

### ISSUE THREAD

**Issue by perrier54** [santiagohy/grammar-rules-extraction#12]
Very often, the modification of one of the three patterns is not taken into account and the following message is displayed: _Same patterns as before_

**Comment by s-herrera** [comment]
Yes, this is a problem i can't solve for the moment. It's a streamlit problem. The message it's just a warning to force the user to double check the patterns. 
There's a conflict between wanting to keep the string patterns to not lose them when the page is changed (e.g. go to the Example page) and updating the new input values. 
There is an intermediate and temporary solution: keep trace of the submitted patterns in the sidebar or in other place, and accepted to lose them when the page is changed, knowing that it's always possible to open the new page in a tab.

**Comment by perrier54** [comment]
For moment, I save the modified pattern in the clipboard.

**Comment by s-herrera** [comment]
So yes, it is probably better to keep a trace of the patterns used and to accept to lose them when the page is changed, than to have to do that... I'm going to change this.

**Comment by s-herrera** [comment]
Patterns can now be modified correctly. For that, we implemented some changes.
Now, the values within the text area will disappear when changing pages, but not the information that has already been processed. This will avoid the user from typing again all the patterns (even if the text area is empty). A sentence for each pattern indicates which value is being considered.
This solution is temporary but more user friendly.
