### ISSUE TITLE
Key to cluster

### ISSUE THREAD

**Issue by perrier54** [santiagohy/grammar-rules-extraction#13]
It's a pity that relation features are not allowed to cluster in pattern3, as in `Grew-match`.

**Comment by s-herrera** [comment]
Hi, what do you mean by relation features?

**Comment by perrier54** [comment]
In `Grew`, the labels of relations between nodes are  feature structures For example, the SUD  relation `comp:obj@agent` is represented by the feature structure `{1:comp, 2: obj, deep:agent}` and with `Grew-match`, it is possible to cluster on `d.1`, `d.2`, `d.deep`, and even on `d.label`, which represents the full label of a dependency `d`.

**Comment by s-herrera** [comment]
Ah ok! I will work on that

**Comment by perrier54** [comment]
I discovered that it is possible to cluster on the dependency labels, but only when the dependencies are present in the P1 pattern. When they are in the P2 pattern, it does not work.

**Comment by s-herrera** [comment]
It's now possible to cluster on the dependency labels, using the keys .1, .2 and .deep. It's necessary to update the app and the opam packages (see README)
