### ISSUE TITLE
% of P1 & P3

### ISSUE THREAD

**Issue by perrier54** [santiagohy/grammar-rules-extraction#6]
We consider the corpus [fr_gsd-sud-train_sud.txt](https://github.com/santiagohy/grammar-rules-extraction/files/9251419/fr_gsd-sud-train_sud.txt).
We apply the following patterns:
_P1: pattern{G[upos=AUX|VERB]; D[upos=PRON];D <G}
P2: pattern{G -[comp:pred]-> D}
P3: pattern{G[lemma="apparaître"|demeurer|devenir|"être"|rester]; D[lemma=le|que]}_
The application gives 76,67 % of P1&P3, whereas `Grew-match` gives 100% (http://universal.grew.fr/?custom=62ea6df5dda28). Even if `Grew-match` works on a larger corpus, the difference is not understandable.

**Comment by s-herrera** [comment]
Hi, 
I think you are comparing the results obtained on the SUD corpus (in the app) with those obtained on the UD corpus (Grew-match).

**Comment by perrier54** [comment]
Sorry for this inattention !
