### ISSUE TITLE
Line breaks in the definition of  patterns

### ISSUE THREAD

**Issue by perrier54** [santiagohy/grammar-rules-extraction#8]
The use of line breaks in the definition of a pattern is not neutral. It can lead to errors in the counting of occurrences in the corpus matching the pattern.
For example, I use the corpus [fr_gsd-sud-train_sud.txt](https://github.com/santiagohy/grammar-rules-extraction/files/9267379/fr_gsd-sud-train_sud.txt).
I applied the following patterns : 

_P1:  pattern{G[upos=AUX]; D[upos=VERB];G <D; 
G[upos=AUX,lemma="être",VerbForm=Part,Tense=Past]; D[upos=VERB,VerbForm=Part,Tense=Past]}_

_P2: pattern{G -[comp:aux@pass]-> D}_

The total of occurrences matching P1 given by the system is 14449, which is false.

I change P1 with:
_P'1: pattern{G[upos=AUX]; D[upos=VERB];G <D; G[upos=AUX,lemma="être",VerbForm=Part,Tense=Past]; D[upos=VERB,VerbForm=Part,Tense=Past]}_

The result becomes 590, which is correct.

**Comment by s-herrera** [comment]
Line breaks will be ignored, and they will have a neutral behavior.
