### ISSUE TITLE
Update of the corpus

### ISSUE THREAD

**Issue by perrier54** [santiagohy/grammar-rules-extraction#9]
When the corpus is modified and we want to upload the new version with the same file name, no upload is performed.

**Comment by santiagohy** [comment]
I changed the structure of the script. Each time the "upload" button is clicked it reloads the corpus. However, it remains in memory until you click this button again.

**Comment by s-herrera** [comment]
I changed the structure of the script. Each time the "upload" button is clicked it reloads the corpus. However, it remains in memory until you click this button again.
